version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../:/app
    environment:
      - PYTHONPATH=/app
